version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
      time: "18:00"
      timezone: "Europe/London"
    labels:
      - "dependencies"
    ignore:
      - dependency-name: "github.com/evanw/esbuild"
        update-types: ["version-update:semver-patch"]
