name: releasebuild
on:
  push:
    branches:
      - master
    tags:
      - v*
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Generate tags
        id: tags
        uses: greboid/docker-tags-action@v2.0.0
      - name: Build for Linux
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -ldflags '-extldflags "-static"' -o dist/linux-${{ steps.tags.outputs.version}}-amd64 .
      - name: Build for Windows
        run: CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -a -ldflags '-extldflags "-static"' -o dist/windows-${{ steps.tags.outputs.version}}-amd64 .
      - name: Build for MacOS AMD64
        run: CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -a -ldflags '-extldflags "-static"' -o dist/darwin-${{ steps.tags.outputs.version}}-arm64 .
      - name: Build for MacOS ARM64
        run: CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -a -ldflags '-extldflags "-static"' -o dist/darwin-${{ steps.tags.outputs.version}}-amd64 .
      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            dist/linux-${{ steps.tags.outputs.version}}-amd64
            dist/windows-${{ steps.tags.outputs.version}}-amd64
            dist/darwin-${{ steps.tags.outputs.version}}-arm64
            dist/darwin-${{ steps.tags.outputs.version}}-amd64